autoDetectedPackages:
- com.example.ai
- com.example.api.client
- com.example.api.config
- com.example.api.domain
- com.example.api.enums
- com.example.auth.config
- com.example.auth.domain
- com.example.auth.enums
- com.example.auth.util
- com.example.cart
- com.example.checkout
- com.example.common.advice
- com.example.common.cache
- com.example.common.config
- com.example.common.domain
- com.example.common.exception
- com.example.common.interceptor
- com.example.common.util
- com.example.gateway
- com.example.order
- com.example.payment
- com.example.product
- com.example.user
enableAutoDetect: true
entryDisplayConfig: null
funcDisplayConfig: null
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
maxColSize: null
maxNumFirst: null
maxNumFirstImportant: null
maxNumHash: null
maxNumHashImportant: null
maxObjectDepth: null
maxStrSize: null
name: xcodemap-filter
openMainWindow: null
recordMode: null
sourceDisplayConfig: null
startOnDebug: null
