server:
  port: 8086

ecommerce:
  database:
    host: @database.host@
    port: @database.port@
    user: @database.user@
    pwd: @database.pwd@
    table: db_payment
  knife4j:
    title: 支付服务
    description: 支付服务
  sentinel:
    dashboard: @sentinel.dashboard@
  nacos:
    dashboard: @nacos.dashboard@
  redis:
    cluster-addr: @redis.cluster-addr@
    expire-hour: 4
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    virtual: /
    user: @rabbitmq.user@
    pwd: @rabbitmq.pwd@



debug: true
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
    com:
        alibaba:
            cloud:
              sentinel: debug